extends: default
rules:
  line-length:
    max: 300
  truthy:
    allowed-values: ["true", "false"]
  comments:
    min-spaces-from-content: 1
  new-line-at-end-of-file: disable
  document-start: disable